/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e4e2e2',
        'outline': '#7b7483',
        'surface-container': '#efeded',
        'outline-variant': '#ccc3d3',
        'secondary': '#655a72',
        'on-error-container': '#93000a',
        'error-container': '#ffdad6',
        'tertiary-container': '#63705e',
        'tertiary-fixed': '#d9e7d0',
        'on-secondary-fixed': '#21172c',
        'on-tertiary-container': '#e5f3dc',
        'on-primary-fixed-variant': '#572e99',
        'primary-container': '#7e57c2',
        'on-surface-variant': '#4a4452',
        'inverse-on-surface': '#f2f0f0',
        'surface': '#fbf9f8',
        'primary-fixed': '#ebdcff',
        'secondary-container': '#eadaf7',
        'on-primary-fixed': '#260058',
        'on-primary-container': '#f6ecff',
        'secondary-fixed-dim': '#d0c1dd',
        'on-primary': '#ffffff',
        'inverse-surface': '#303030',
        'on-secondary-container': '#6a5e76',
        'inverse-primary': '#d4bbff',
        'on-surface': '#1b1c1c',
        'error': '#ba1a1a',
        'surface-container-high': '#eae8e7',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#6f48b2',
        'background': '#fbf9f8',
        'surface-variant': '#e4e2e2',
        'on-background': '#1b1c1c',
        'tertiary-fixed-dim': '#bdcbb5',
        'primary': '#653da7',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#edddfa',
        'surface-bright': '#fbf9f8',
        'on-tertiary-fixed-variant': '#3e4a39',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#d4bbff',
        'on-secondary-fixed-variant': '#4d4259',
        'on-tertiary-fixed': '#131e10',
        'surface-dim': '#dbdad9',
        'tertiary': '#4b5846',
        'surface-container-low': '#f5f3f3'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      spacing: {
        'space-xs': '0.375rem',
        'space-xl': '2.5rem',
        'margin': '2.5rem',
        'space-md': '1.25rem',
        'gutter-mobile': '1rem',
        'gutter': '1.5rem',
        'space-sm': '0.75rem',
        'margin-mobile': '1.25rem',
        'space-lg': '1.75rem'
      },
      fontFamily: {
        'title-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'label-md': ['Inter'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'numeric-metric': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'display-hero-mobile': ['Plus Jakarta Sans'],
        'label-sm': ['Inter'],
        'body-md': ['Plus Jakarta Sans'],
        'display-hero': ['Plus Jakarta Sans'],
        'title-md': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans']
      },
      fontSize: {
        'title-lg': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'numeric-metric': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-hero-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'display-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.005em', fontWeight: '400' }]
      }
    },
  },
  plugins: [],
}
